# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 312)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(140, 50, 185, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.number = QtWidgets.QCheckBox(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(130, 110, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(10)
        self.number.setFont(font)
        self.number.setObjectName("number")
        self.alfavit = QtWidgets.QCheckBox(self.centralwidget)
        self.alfavit.setGeometry(QtCore.QRect(130, 130, 174, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(10)
        self.alfavit.setFont(font)
        self.alfavit.setObjectName("alfavit")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(130, 80, 112, 16))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(10)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.zgeneruvatu = QtWidgets.QPushButton(self.centralwidget)
        self.zgeneruvatu.setGeometry(QtCore.QRect(180, 160, 95, 23))
        self.zgeneruvatu.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zgeneruvatu.setFont(font)
        self.zgeneruvatu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.zgeneruvatu.setStyleSheet("color:rgb(0, 0, 0);\n"
"background-color:rgb(198, 255, 222);\n"
"border: 2px solid black;\n"
"\n"
"")
        self.zgeneruvatu.setObjectName("zgeneruvatu")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))
        self.number.setText(_translate("MainWindow", "Використовувати числа"))
        self.alfavit.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))
        self.zgeneruvatu.setText(_translate("MainWindow", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
